#ifndef __dialog_constraint_layer_selection__
#define __dialog_constraint_layer_selection__

/**
@file
Subclass of DIALOG_CONSTRAINT_LAYER_SELECTION_BASE, which is generated by wxFormBuilder.
*/

#include "dialog_constraint_layer_selection_base.h"

//// end generated include

/** Implementing DIALOG_CONSTRAINT_LAYER_SELECTION_BASE */
class DIALOG_CONSTRAINT_LAYER_SELECTION : public DIALOG_CONSTRAINT_LAYER_SELECTION_BASE
{
	public:
		/** Constructor */
		DIALOG_CONSTRAINT_LAYER_SELECTION( wxWindow* parent );
	//// end generated class members
	
};

#endif // __dialog_constraint_layer_selection__
